### ISSUE TITLE
Wrong store_id set for image when importing products

### ISSUE THREAD

**Issue by jorgb90** [dealer4dealer/magento2-restapi#19]
When a product gets imported from Exact into Magento 2 it somehow saves images on store_id 1 instead of 0 in table 'CATALOG_PRODUCT_ENTITY_VARCHAR', causing to show placeholders for other storeviews.

Maybe it has something to do with this? https://github.com/magento/magento2/issues/10687

**Comment by HenriNijborg** [comment]
Due to the following issues we use a workaround:
* https://github.com/magento/magento2/issues/11648
* https://github.com/magento/magento2/issues/11768

Please send an email to the dealer4dealer servicedesk because we don't have any logic for this in this extension. It's all managed by the xCore. Therefor I will close this issue.
